import React from "react";
import Head from "next/head";
import { api } from "~/utils/api";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";
import Card from "~/components/card";
import RightSection from "../components/rightSection";
import Hunter from "../../public/hunter.jpg";
import Onepiece from "../../public/onePiece.jpg";
import LandScape from "../../public/landscape.webp"

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className="flex flex-col min-h-screen bg-gray-100 py-4 pt-20">
        
        <div className="flex justify-center">
          <div className="w-[calc(100%-160px)] flex gap-4">
            <div id="left" className="hidden w-1/6 min-w-[240px] sm:flex flex-col text-gray-700 ">
              <Sidebar />
            </div>

            <div id="middle" className="flex-1 min-w-[400px] max-w-[750px] flex flex-col gap-4 ">
              <div className="flex gap-4">
                <button className="text-lg font-semibold hover:bg-white hover:text-[#3b49df] px-4 py-2 rounded-md text-black">Relevant</button>
                <button className="text-lg hover:bg-white hover:text-[#3b49df] px-4 py-2 rounded-md text-[#404040]">Latest</button>
                <button className="text-lg hover:bg-white hover:text-[#3b49df] px-4 py-2 rounded-md text-[#404040]">Top</button>
              </div>
              <Card 
              imageSrc={LandScape} 
              username="@Lord_Laxus" 
              title="Title - Hello Hello" 
              content="Finally made this wohoo, just need to connect to backend. Check back soon for updates. Thank you for coming to my not so famous TED talk."
            />
            <Card 
              imageSrc={Onepiece} 
              username="@GodFather69" 
              title="Title - Hello Hello" 
              content="Finally made this wohoo, just need to connect to backend. Check back soon for updates. Thank you for coming to my not so famous TED talk."
            />
            <Card 
              imageSrc={Hunter} 
              username="@Lord_Explosion_Murder" 
              title="Title - Hello Hello" 
              content="Finally made this wohoo, just need to connect to backend. Check back soon for updates. Thank you for coming to my not so famous TED talk."
            />
            </div>

            <div id="right" className="hidden w-1/4 min-w-[350px] flex-col lg:flex bg-gray-50">
              <RightSection />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
